# Everything here is gated on var.root_domain — blank (the default) means
# none of it is created, and the app keeps working on raw Cloud Run
# *.run.app URLs exactly as before. See variables.tf for the Search Console
# domain-verification prerequisite the domain mapping resources need.
locals {
  app_domain     = "app.${var.root_domain}"
  api_domain     = "api.${var.root_domain}"
  mailgun_domain = "mg.${var.root_domain}"
}

resource "google_dns_managed_zone" "primary" {
  count       = var.root_domain != "" ? 1 : 0
  name        = "ehr-translator"
  dns_name    = "${var.root_domain}."
  description = "app/api custom domains + Mailgun sending-domain records for ${var.root_domain}."

  depends_on = [google_project_service.required]
}

# Cloud Run domain mappings for a non-apex host (app./api., not the bare
# root domain) always resolve via this exact, fixed CNAME target — Google's
# documented value, not something the domain_mapping resource's own
# computed attributes need to supply, so no apply-time ordering issue here.
resource "google_dns_record_set" "app" {
  count        = var.root_domain != "" ? 1 : 0
  name         = "${local.app_domain}."
  managed_zone = google_dns_managed_zone.primary[0].name
  type         = "CNAME"
  ttl          = 300
  rrdatas      = ["ghs.googlehosted.com."]
}

resource "google_dns_record_set" "api" {
  count        = var.root_domain != "" ? 1 : 0
  name         = "${local.api_domain}."
  managed_zone = google_dns_managed_zone.primary[0].name
  type         = "CNAME"
  ttl          = 300
  rrdatas      = ["ghs.googlehosted.com."]
}

# Mailgun's documented SMTP relay MX records — same for every sending
# domain, unlike the DKIM value below.
resource "google_dns_record_set" "mailgun_mx" {
  count        = var.root_domain != "" ? 1 : 0
  name         = "${local.mailgun_domain}."
  managed_zone = google_dns_managed_zone.primary[0].name
  type         = "MX"
  ttl          = 3600
  rrdatas      = ["10 mxa.mailgun.org.", "10 mxb.mailgun.org."]
}

resource "google_dns_record_set" "mailgun_spf" {
  count        = var.root_domain != "" ? 1 : 0
  name         = "${local.mailgun_domain}."
  managed_zone = google_dns_managed_zone.primary[0].name
  type         = "TXT"
  ttl          = 3600
  rrdatas      = ["\"v=spf1 include:mailgun.org ~all\""]
}

# Domain-specific — generated by Mailgun only after mg.ROOT_DOMAIN is added
# as a sending domain in their dashboard, so this can't have a real default.
# Skipped (not a hard failure) while var.mailgun_dkim_value is blank.
resource "google_dns_record_set" "mailgun_dkim" {
  count        = var.root_domain != "" && var.mailgun_dkim_value != "" ? 1 : 0
  name         = "${var.mailgun_dkim_selector}._domainkey.${local.mailgun_domain}."
  managed_zone = google_dns_managed_zone.primary[0].name
  type         = "TXT"
  ttl          = 3600
  rrdatas      = ["\"${var.mailgun_dkim_value}\""]
}

# Anti-spoofing policy for the root domain itself, not just the mg.
# subdomain Mailgun sends from — p=none (report-only, no rejection) is a
# deliberately conservative starting point; tighten to quarantine/reject
# once you've watched real mail flow for a while.
resource "google_dns_record_set" "dmarc" {
  count        = var.root_domain != "" ? 1 : 0
  name         = "_dmarc.${var.root_domain}."
  managed_zone = google_dns_managed_zone.primary[0].name
  type         = "TXT"
  ttl          = 3600
  rrdatas      = ["\"v=DMARC1; p=none;\""]
}
