# Generated by Django 5.2.16 on 2026-07-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="findings",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
