# Generated by Django 5.2.16 on 2026-07-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_findings"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="document",
            name="display_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
