# Generated by Django 5.2.16 on 2026-07-21 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_content_hash_document_display_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("content_hash", ""), _negated=True),
                fields=("owner", "content_hash"),
                name="unique_owner_content_hash",
            ),
        ),
    ]
