# Generated by Django 5.2.16 on 2026-07-30 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_documentaccesslog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_tour_sample",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_tour_sample", True)),
                fields=("is_tour_sample",),
                name="unique_tour_sample",
            ),
        ),
    ]
