# Generated by Django 5.2.16 on 2026-09-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_document_is_tour_sample_document_unique_tour_sample"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="search_context",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
